remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Sebastian Castaño Restrepo
submodulo: Introduccion a la programacion 
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/github-pages-7777b.appspot.com/o/IMG20230331173434%5B1%5D.jpg?alt=media&token=9f540e76-bc79-4124-957f-c430112a26c2